### ISSUE TITLE
Package creates an audit.log file even when not yet installed

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.fingerpointing#31] opened 2016-03-28 22:01 UTC
Also, the following message is logged in the standard event log:

```
2016-03-28 18:56:05 INFO collective.fingerpointing Start logging audit information to audit.log
```

**Comment by jensens** [comment] 2017-11-22 01:53
this should be fixed with the refactoring in #68 - I simply removed the message and logged it to the default logger. Also audit-file is created on first emit and not before.

**Comment by hvelarde** [comment] 2017-11-22 13:59
no, is not, but I don't know if this must be considered a bug or not.

**Comment by jensens** [comment] 2017-11-22 14:16
Its a bit ugly, but not a real bug.

**Closed** 2017-11-22 14:33 UTC
Labels: bug

**Comment by jensens** [comment] 2017-11-22 15:53
btw.: I manually tested it here, the problem is gone. I stopped the instance, cleared my ``./var/log`` and then fired up the instance. Theres no file.
Even if I load the @@fingerpointing-audit-log view -> no file

When do something which triggers an event log, then the file is created.
